{
  checkOpeness();
  checkIfActive();
  try {
    nestedCommit.complete();
  }
 catch (  RuntimeException e) {
    OLogManager.instance().debug(this,"Error on transaction commit",e);
    for (    ODatabaseListener listener : browseListeners())     try {
      listener.onBeforeTxRollback(ODatabaseDocumentTx.this);
    }
 catch (    Throwable t) {
      OLogManager.instance().error(this,"Error before transaction rollback",t);
    }
    currentTx.rollback(false,0);
    getLocalCache().clear();
    for (    ODatabaseListener listener : browseListeners())     try {
      listener.onAfterTxRollback(ODatabaseDocumentTx.this);
    }
 catch (    Throwable t) {
      OLogManager.instance().error(this,"Error after transaction rollback",t);
    }
    throw e;
  }
  for (  ODatabaseListener listener : browseListeners())   try {
    listener.onAfterTxCommit(ODatabaseDocumentTx.this);
  }
 catch (  Exception e) {
    final String message="Error after the transaction has been committed. The transaction remains valid. The exception caught was on execution of " + listener.getClass() + ".onAfterTxCommit()";
    OLogManager.instance().error(this,message,e);
    throw OException.wrapException(new OTransactionBlockedException(message),e);
  }
}
