{
  try {
    return current < end || input.ready();
  }
 catch (  IOException e) {
    throw OException.wrapException(new OIOException("Error in ready"),e);
  }
}
