{
  try {
    return current < end || input.ready();
  }
 catch (  IOException e) {
    throw new OIOException("Error in ready",e);
  }
}
